version: 2.1

parameters:
  head_ref:
    type: string
    default: NONE
  base_ref:
    type: string
    default: NONE
executors:
  jdk11-docker:
    docker:
      - image: cimg/openjdk:21.0.5
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
  vm:
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    machine:
      image: ubuntu-2404:2024.11.1

jobs:
  build_and_test:
    executor: vm
    resource_class: large
    working_directory: ~/mac
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}
            - mac-java-{{ .Branch }}-
            - mac-java-
      - run:
          name: "Build and test"
          command: |
            sudo sysctl -w vm.overcommit_memory=1
            mkdir -p "$HOME/.m2/repository"
            docker run --rm --privileged \
              -e ACTIVEPIVOT_LICENSE -e ARTIFACTORY_USER -e ARTIFACTORY_TOKEN \
              -v "$HOME/.m2/repository:/tmp/repository" \
              -v "$PWD:/home/circleci/mac" \
              -w /home/circleci/mac -u root \
              cimg/openjdk:21.0.5 \
              mvn package --settings .circleci/circleci-settings.xml -Dmaven.repo.local=/tmp/repository
      - save_cache:
          paths: [ ~/.m2/repository ]
          key: mac-java-{{ .Branch }}-{{ checksum "pom.xml" }}

workflows:
  version: 2
  check:
    jobs:
      - build_and_test:
          context: rnd-server
